#!/bin/bash
# Script to remove large model files from Git repository

echo "Removing large model files from Git tracking..."
echo "(Files will remain on your local machine)"

cd /home/mubeen/ai

# Remove from Git (but keep locally)
git rm --cached models/trained/*.pkl 2>/dev/null || echo "Some files already removed"

# Commit the removal
git commit -m "Remove large model files from repository (can be regenerated by training)"

echo ""
echo "✅ Large files removed from Git tracking"
echo ""
echo "Next step: Run 'git push origin main' to update GitHub"
echo ""
echo "Note: Model files still exist locally and can be regenerated with:"
echo "  python train.py --generate --samples 10000"
